# .github/workflows/preview.yml
name: Deploy PR previews

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1.4.6
        with:
          token: ${{secrets.GITHUB_TOKEN }}
          preview-branch: main
          source-dir: .
          umbrella-dir: pr-preview
